In [1]:
#!pip install numpy

In [2]:
import numpy as np

In [3]:
my_list = np.arange(10)

In [4]:
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_list ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
customer_purchases = np.array([[45, 43, 41], [34, 36, 37]])

In [7]:
customer_purchases

array([[45, 43, 41],
       [34, 36, 37]])

In [8]:
customer_purchases.shape

(2, 3)

In [9]:
customer_purchases[0]

array([45, 43, 41])

In [10]:
customer_purchases[0].mean()

43.0

In [11]:
customer_purchases[0].std()

1.632993161855452

In [13]:
customer_purchases[0].min()

41

In [14]:
customer_purchases.max()

45

In [15]:
image = np.random.rand(64, 64, 3)

In [16]:
image.shape

(64, 64, 3)

In [17]:
image.max()

0.9999956847363707

In [18]:
image.min()

0.00011543902275412687

In [19]:
btc_prices = np.array([10000, 10500, 10250])
eth_prices = np.array([1000, 1050, 1025])

In [21]:
btc_returns = (btc_prices[1:] - btc_prices[:-1]) / btc_prices[:-1]
eth_returns = (eth_prices[1:] - eth_prices[:-1]) / eth_prices[:-1]

In [22]:
btc_returns

array([ 0.05      , -0.02380952])

In [23]:
eth_returns

array([ 0.05      , -0.02380952])

In [24]:
dot_product = np.dot(btc_returns, eth_returns)

In [25]:
print('Dot product: ', dot_product)

Dot product:  0.0030668934240362816
