In [1]:
movies = []

In [2]:
type(movies)

list

In [3]:
movies.append('Matrix')

In [4]:
movies

['Matrix']

In [5]:
movies.append('Top Gun')

In [6]:
movies

['Matrix', 'Top Gun']

In [7]:
movies = movies + ['Fast and Furious', 'Ten Commandments']

In [8]:
#movies.append(['Fast and Furious', 'Ten Commandments'])

In [9]:
#movies

In [10]:
movies

['Matrix', 'Top Gun', 'Fast and Furious', 'Ten Commandments']

In [11]:
movies

['Matrix', 'Top Gun', 'Fast and Furious', 'Ten Commandments']

In [12]:
movies[0]

'Matrix'

In [13]:
movies[-1]

'Ten Commandments'

In [14]:
len(movies)

4

In [15]:
movies.sort()

In [16]:
movies

['Fast and Furious', 'Matrix', 'Ten Commandments', 'Top Gun']

In [17]:
movies.sort(reverse=True)

In [18]:
movies

['Top Gun', 'Ten Commandments', 'Matrix', 'Fast and Furious']

In [19]:
movies.insert(2, 'Star Wars')

In [20]:
movies

['Top Gun', 'Ten Commandments', 'Star Wars', 'Matrix', 'Fast and Furious']

In [21]:
movies.pop() # Treat the list as a Stack

'Fast and Furious'

In [22]:
movies

['Top Gun', 'Ten Commandments', 'Star Wars', 'Matrix']

In [23]:
movies.pop(0)

'Top Gun'

In [24]:
movies

['Ten Commandments', 'Star Wars', 'Matrix']

In [25]:
movies_cp = movies[:]  # Copy the content of the list not the object reference.

In [26]:
movies_cp.append("Mission Impossible")

In [27]:
movies_cp

['Ten Commandments', 'Star Wars', 'Matrix', 'Mission Impossible']

In [28]:
movies

['Ten Commandments', 'Star Wars', 'Matrix']

In [29]:
my_list = list(range(20))

In [30]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [31]:
fixed_list = tuple(movies)

In [32]:
fixed_list

('Ten Commandments', 'Star Wars', 'Matrix')

In [33]:
fixed_list.append('Gone with the Wind")

SyntaxError: EOL while scanning string literal (1803409388.py, line 1)

In [34]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [35]:
# List comprehensions 

In [36]:
list_times_two = [ element * 2 for element in my_list]

In [37]:
list_times_two

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [38]:
import numpy as np 

In [39]:
new_list = np.array(my_list)

In [40]:
new_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
my_list_times_two = new_list * 2 

In [48]:
my_list_times_two

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [50]:
my_list_squared = new_list ** 2

In [52]:
my_list_squared

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])