In [1]:
my_list = list(range(10))

In [2]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
for element in my_list:
    print(element ** 2)

0
1
4
9
16
25
36
49
64
81


In [4]:
results = []
for element in my_list:
    results.append(element ** 2)

In [5]:
results

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [8]:
# List Comprehensions
results1 = [element ** 2 for element in my_list]

In [13]:
results1

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
even_numbers = []

for element in my_list:

    if (element % 2 == 0):
        even_numbers.append(element)

In [12]:
even_numbers

[0, 2, 4, 6, 8]

In [15]:
import numpy as np

In [16]:
new_array = np.array(my_list)

In [17]:
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
new_array.shape

(10,)

In [23]:
new_array = new_array.reshape(1, 10)

In [24]:
new_array.shape

(1, 10)

In [25]:
new_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
new_array = new_array.reshape(10, 1)

In [27]:
new_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
new_array.shape

(10, 1)

In [30]:
# while True:
#     print("Welcome to Dubai!")

In [32]:
counter = 0

while (counter < 10):
    print(f"counter is currently: {counter}")
    counter +=  1 

counter is currently: 0
counter is currently: 1
counter is currently: 2
counter is currently: 3
counter is currently: 4
counter is currently: 5
counter is currently: 6
counter is currently: 7
counter is currently: 8
counter is currently: 9


In [33]:
counter = 0

while (counter < 10):
    if counter == 5:
        break
    print(f"counter is currently: {counter}")
    counter +=  1 

counter is currently: 0
counter is currently: 1
counter is currently: 2
counter is currently: 3
counter is currently: 4


In [37]:
counter = 0

while (counter < 10):
    print(f"counter is currently: {counter}")
    counter +=1
    if counter == 5:
        continue



counter is currently: 0
counter is currently: 1
counter is currently: 2
counter is currently: 3
counter is currently: 4
counter is currently: 5
counter is currently: 6
counter is currently: 7
counter is currently: 8
counter is currently: 9
